export enum EmployeeEnum {
  'accounting assistant',
  'accounting supervisor',
  'administrative officer',
  'assistant manager',
  'assistant manager - corporate environment, health, and safety',
  'associate vice president for construction operations',
  'autocad operator',
  'billing and collection assistant',
  'billing and collection supervisor',
  'business development officer',
  'cad operator',
  'ceo/president',
  'concreting engineer',
  'corporate communications officer',
  'cost control engineer',
  'document controller',
  'electrical engineer',
  'executive assistant',
  'field engineer',
  'formworks engineer',
  'head of commercial and contracts',
  'head of construction operations',
  'head of general and corporate accounting',
  'head of human resources',
  'head of internal audit',
  'head of procurement and materials management',
  'head of tender planning and estimating',
  'head of treasury, billing and collection, insurances and bonds',
  'human resources assistant',
  'human resources officer - engagement and communications',
  'human resources officer - compensation and benefits',
  'human resources officer - talent management',
  'human resources operations supervisor',
  'human resources services coordinator',
  'information technology staff',
  'information technology supervisor',
  'junior estimator',
  'logistics assistant',
  'logistics manager',
  'material inventory assistant',
  'office architect',
  'office engineer',
  'operations assistant',
  'operations supervisor',
  'planning and scheduling manager',
  'planning engineer',
  'precast engineer',
  'preventive maintenance technician',
  'project accountant',
  'project architect',
  'project engineer',
  'project human resources',
  'project manager',
  'project nurse',
  'project supervisor',
  'project supervisor - architectural',
  'purchasing assistant',
  'purchasing supervisor',
  'quality assurance and quality control architect',
  'quality assurance and quality control engineer',
  'quality assurance and quality control interim supervisor',
  'quality assurance and quality control manager',
  'quality control supervisor - line and grade control',
  'rebar engineer',
  'safety officer',
  'safety-in-charge',
  'senior cost control engineer',
  'senior estimator',
  'senior project engineer',
  'senior project manager',
  'senior supervisor - corporate procurement and materials management',
  'site architect',
  'site engineer',
  'site procurement officer (spo)',
  'software developer manager',
  'software developer supervisor',
  'stock analyst',
  'surveyor supervisor',
  'technical assistant',
  'toolkeeper-in-charge',
  'treasury assistant',
  'treasury coordinator',
  'treasury supervisor',
  'warehouse man',
  'web developer',
}

export enum RankEnum {
  'executive',
  'assistant vice president',
  'manager',
  'assistant manager',
  'senior supervisory',
  'supervisory',
  'rank and file',
}

export enum DepartmentsEnum {
  'ceo',
  'cfo',
  'ops',
  'bdm',
  'ccd',
  'cga',
  'esh',
  'hel',
  'hrd',
  'itd',
  'iad',
  'ocd',
  'pmm',
  'qac',
  'svd',
  'tpe',
  'tod',
  'tre',
}

export enum LocationsEnum {
  'vho',
  'vcw',
  'mdt',
  'trz',
  'gil',
  'ibp',
  'sth',
  'blm',
  'chr',
  'hil',
  'vin',
  'old',
  'sha',
  'sol',
}

export enum EmploymentStatusEnum {
  'probationary',
  'resigned',
  'terminated',
  'leave of absence',
  'separated',
}

export enum EmploymentTypeEnum {
  'regular',
  'project employee',
}

export enum CivilStatusEnum {
  'single',
  'married',
  'common-law/live-in',
  'widowed',
  'separated',
}

export enum ReligionEnum {
  'aglipayan (philippine independence church)',
  'ang dating daan',
  'assemblies of god (ilocos norte)',
  'baptist world alliance',
  'buddhist',
  'christian',
  'church of jesus christ and the latter day saints',
  'church of the nazarene',
  'el shaddai',
  'evangelical',
  'god world missions church',
  'hindu',
  'iglesia ni cristo (church of christ)',
  'indigenous religions',
  "jehovah's witnesses",
  'judaism',
  'lutheran church in the philippines',
  'mennonites',
  'methodist',
  'mount banahaw holy confederation',
  'muslim/islamic',
  'philippine benevolent missionary association (pbma)',
  'philippine episcopal church',
  'presbyterian',
  'protestants',
  'rizalistas',
  'roman catholic',
  'seventh-day adventists (central phil. union conf.)',
  'unitarian',
  'united church of christ in the philippines',
  'worldwide church of god',
  'atheists (did not identify religion)',
  'others, please specify',
}
export enum GenderEnum {
  'male',
  'female',
}

export enum HighestEducationalAttainmentEnum {
  'primary education – kinder to grade 6',
  'lower secondary education – grade 7 to 10',
  'upper secondary education – grade 11 to 12',
  'associates degree',
  'no degree - less than 1 year of college/university',
  'no degree - more than 1 year of college/university',
  'undergraduate (bachelor’s degree)',
  'postgraduate (master’s degree)',
  'doctoral (phd)',
  'technical and vocational education',
}

export enum DisciplinaryActionsEnum {
  'verbal warning',
  '1st written warning',
  'final written warning',
  'suspension',
  'termination',
}

export enum UserGroupEnum {
  'hr admin',
  'system admin',
  'approver',
  'employee',
}

export enum AutoCredentialEnum {
  'hr admin',
  'system admin',
  'approver',
}

export enum RelationEnum {
  'parents',
  'siblings',
  'spouse',
  'children',
}

export enum NotAllowedToEdit {
  'employeeno',
  'position',
  'rank',
  'department',
  'location',
  'usergroup',
  'employmentstatus',
  'civilstatus',
}

export enum PayTypeEnum {
  'bi monthly',
  'weekly',
}

export enum PaymentMethodEnum {
  'cash',
  'check',
  'payroll account',
}

export enum CitizenshipEnum {
  'afghanistan',
  'albania',
  'algeria',
  'andorra',
  'angola',
  'antigua and barbuda',
  'argentina',
  'armenia',
  'australia',
  'austria',
  'azerbaijan',
  'bahamas',
  'bahrain',
  'bangladesh',
  'barbados',
  'belarus',
  'belgium',
  'belize',
  'benin',
  'bhutan',
  'bolivia',
  'bosnia and herzegovina',
  'botswana',
  'brazil',
  'brunei',
  'bulgaria',
  'burkina faso',
  'burundi',
  'cabo verde',
  'cambodia',
  'cameroon',
  'canada',
  'central african republic (car)',
  'chad',
  'chile',
  'china',
  'colombia',
  'comoros',
  'congo, democratic republic of the',
  'congo, republic of the',
  'costa rica',
  "cote d'ivoire",
  'croatia',
  'cuba',
  'cyprus',
  'czechia',
  'denmark',
  'djibouti',
  'dominica',
  'dominican republic',
  'ecuador',
  'egypt',
  'el salvador',
  'equatorial guinea',
  'eritrea',
  'estonia',
  'eswatini',
  'ethiopia',
  'fiji',
  'finland',
  'france',
  'gabon',
  'gambia',
  'georgia',
  'germany',
  'ghana',
  'greece',
  'grenada',
  'guatemala',
  'guinea',
  'guinea-bissau',
  'guyana',
  'haiti',
  'honduras',
  'hungary',
  'iceland',
  'india',
  'indonesia',
  'iran',
  'iraq',
  'ireland',
  'israel',
  'italy',
  'jamaica',
  'japan',
  'jordan',
  'kazakhstan',
  'kenya',
  'kiribati',
  'kosovo',
  'kuwait',
  'kyrgyzstan',
  'laos',
  'latvia',
  'lebanon',
  'lesotho',
  'liberia',
  'libya',
  'liechtenstein',
  'lithuania',
  'luxembourg',
  'madagascar',
  'malawi',
  'malaysia',
  'maldives',
  'mali',
  'malta',
  'marshall islands',
  'mauritania',
  'mauritius',
  'mexico',
  'micronesia',
  'moldova',
  'monaco',
  'mongolia',
  'montenegro',
  'morocco',
  'mozambique',
  'myanmar',
  'namibia',
  'nauru',
  'nepal',
  'netherlands',
  'new zealand',
  'nicaragua',
  'niger',
  'nigeria',
  'north korea',
  'north macedonia',
  'norway',
  'oman',
  'pakistan',
  'palau',
  'palestine',
  'panama',
  'papua new guinea',
  'paraguay',
  'peru',
  'philippines',
  'poland',
  'portugal',
  'qatar',
  'romania',
  'russia',
  'rwanda',
  'saint kitts and nevis',
  'saint lucia',
  'saint vincent and the grenadines',
  'samoa',
  'san marino',
  'sao tome and principe',
  'saudi arabia',
  'senegal',
  'serbia',
  'seychelles',
  'sierra leone',
  'singapore',
  'slovakia',
  'slovenia',
  'solomon islands',
  'somalia',
  'south africa',
  'south korea',
  'south sudan',
  'spain',
  'sri lanka',
  'sudan',
  'suriname',
  'sweden',
  'switzerland',
  'syria',
  'taiwan',
  'tajikistan',
  'tanzania',
  'thailand',
  'timor-leste',
  'togo',
  'tonga',
  'trinidad and tobago',
  'tunisia',
  'turkey',
  'turkmenistan',
  'tuvalu',
  'uganda',
  'ukraine',
  'united arab emirates (uae)',
  'united kingdom (uk)',
  'united states of america (usa)',
  'uruguay',
  'uzbekistan',
  'vanuatu',
  'vatican city (holy see)',
  'venezuela',
  'vietnam',
  'yemen',
  'zambia',
  'zimbabwe',
}

export enum EducationLevelEnum {
  'elementary',
  'secondary',
  'tertiary',
  'post graduate',
  'others',
}
