import { aggregateFormatDate } from 'src/utils/aggregate_helper';

export interface EmployeeI {
  employeeNo: string;
  isActive: boolean;
  userGroup: string;
  firstName: string;
  lastName: string;
  middleName: string;
  suffix: string;
  birthDate: Date;
  gender: string;
  civilStatus: string;
  citizenship: string;
  religion: string;
  personalContactNumber: string;
  personalEmail: string;
  presentAddress: JSON;
  permanentAddress: JSON;
  educationalBackground: JSON;
  employmentRecords: JSON;
  govtProfExamsPassed: JSON;
  licensesCertifications: JSON;
  familyBackground: JSON;
  emergencyContact: JSON;
  companyContactNumber: string;
  companyEmail: string;
  position: string;
  department: string;
  location: string;
  reportsTo: string;
  dateHired: Date;
  dateInactive: Date;
  endOfProbationary: Date;
  contractEndDate: Date;
  rank: string;
  employmentStatus: string;
  employmentType: string;
  sss: string;
  philHealth: string;
  pagIbig: string;
  tin: string;
  numberOfDependents: number;
  taxExemption: string;
  basicPay: number;
  payRateType: string;
  paymentMethod: string;
  payrollGroup: string;
  deductionSSS: number;
  deductPhilhealth: string;
  deductHMDF: number;
  fixedContributionRate: string;
  deductWithholdingTax: number;
  allowanceDetails: JSON;
  payrollBankAccount: JSON;
  leave_requests?: any;
}

export const defaultItems = {
  employeeNo: '$employeeNo',
  isActive: '$isActive',
  userGroup: '$userGroup',
  firstName: '$firstName',
  lastName: '$lastName',
  middleName: '$middleName',
  suffix: '$suffix',
  birthDate: '$birthDate',
  gender: '$gender',
  civilStatus: '$civilStatus',
  citizenship: '$citizenship',
  religion: '$religion',
  personalContactNumber: '$personalContactNumber',
  personalEmail: '$personalEmail',
  presentAddress: '$presentAddress',
  permanentAddress: '$permanentAddress',
  educationalBackground: '$educationalBackground',
  employmentRecords: '$employmentRecords',
  govtProfExamsPassed: '$govtProfExamsPassed',
  licensesCertifications: '$licensesCertifications',
  familyBackground: '$familyBackground',
  emergencyContact: '$emergencyContact',
  companyContactNumber: '$companyContactNumber',
  companyEmail: '$companyEmail',
  position: '$position',
  department: '$department',
  location: '$location',
  reportsTo: '$reportsTo',
  dateHired: '$dateHired',
  dateInactive: '$dateInactive',
  endOfProbationary: '$endOfProbationary',
  contractEndDate: '$contractEndDate',
  rank: '$rank',
  employmentStatus: '$employmentStatus',
  employmentType: '$employmentType',
  employeeBenefits: '$employeeBenefits',
  sss: '$sss',
  philHealth: '$philHealth',
  pagIbig: '$pagIbig',
  tin: '$tin',
  numberOfDependents: '$numberOfDependents',
  taxExemption: '$taxExemption',
  basicPay: '$basicPay',
  payRateType: '$payRateType',
  paymentMethod: '$paymentMethod',
  payrollGroup: '$payrollGroup',
  deductionSSS: '$deductionSSS',
  deductPhilhealth: '$deductPhilhealth',
  deductHMDF: '$deductHMDF',
  fixedContributionRate: '$fixedContributionRate',
  deductWithholdingTax: '$deductWithholdingTax',
  allowanceDetails: '$allowanceDetails',
  payrollBankAccount: '$payrollBankAccount',
  employmentLastUpdate: '$employmentLastUpdate',
  jobLastUpdate: '$jobLastUpdate',
  type: '$type',
  effectiveDate: '$effectiveDate',
  remarks: '$remarks',
};

export const defaultSet = {
  dateInactive: aggregateFormatDate('dateInactive'),
  endOfProbationary: aggregateFormatDate('endOfProbationary'),
  dateHired: aggregateFormatDate('dateHired'),
  contractEndDate: aggregateFormatDate('contractEndDate'),
  jobLastUpdate: aggregateFormatDate('jobLastUpdate'),
  employmentLastUpdate: aggregateFormatDate('employmentLastUpdate'),
  dateCreated: aggregateFormatDate('dateCreated'),
};
